Repository COSC481W-2024Winter/augmentedDocScanner, pull requests merged in 2024-04, with the labels that each got.

#52 Feature/Change: Generate PDF opens to a new tab
  AugDocumentScanner/controller/controller.js
Labels: enhancement, backend, Sprint 3

#54 Feat: QR code now can be customized by user
  AugDocumentScanner/controller/controller.js
  AugDocumentScanner/test/src/main/java/ADS/test/Tests.java
  AugDocumentScanner/view/pdfgen.html
Labels: improvment, backend, Sprint 3

#55 Feature: refactor crop keystoning
  AugDocumentScanner/controller/controller.js
  AugDocumentScanner/controller/jsqrcode.zip
  AugDocumentScanner/test/croptest.html
  AugDocumentScanner/test/qrpage7.png
  AugDocumentScanner/test/qrpage8.jpg
  AugDocumentScanner/test/qrpage9.jpg
  AugDocumentScanner/test/src/main/java/ADS/test/Tests.java
  AugDocumentScanner/test/src/main/java/ADS/test/distorttest
Labels: bug, improvment, backend, Sprint 3

#61 Qr code fixing
  .gitignore
  AugDocumentScanner/controller/controller.js
  AugDocumentScanner/view/pdfgen.html
Labels: bug
