Repository COSC481W-2024Winter/augmentedDocScanner, pull requests merged in 2024-03, with the labels that each got.

#42 Style and Fix: Make Generate PDF page look consistent with other pages
  AugDocumentScanner/view/about.html
  AugDocumentScanner/view/help.html
  AugDocumentScanner/view/home.html
  AugDocumentScanner/view/pdfgen.html
Labels: frontend, Sprint 2

#45 Style: Improving the UI of the Website
  AugDocumentScanner/view/about.html
  AugDocumentScanner/view/help.html
  AugDocumentScanner/view/home.html
  AugDocumentScanner/view/pdfgen.html
Labels: improvment, frontend, Sprint 2

#47 Feature: progress on cropping ability
  AugDocumentScanner/controller/controller.js
  AugDocumentScanner/test/qr2.png
  AugDocumentScanner/test/qrpage1.png
  AugDocumentScanner/test/qrpage2.png
  AugDocumentScanner/test/qrpage3.png
  AugDocumentScanner/test/qrpage4.png
  AugDocumentScanner/test/qrpage6.jpg
  AugDocumentScanner/test/src/main/java/ADS/test/QRTest.java
  AugDocumentScanner/test/src/main/java/ADS/test/Tests.java
  AugDocumentScanner/test/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  AugDocumentScanner/test/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  AugDocumentScanner/test/test.bash
  AugDocumentScanner/test/test.bat
  AugDocumentScanner/view/home.html
Labels: backend, Sprint 2
