Repository COSC481W-2024Winter/augmentedDocScanner, pull requests merged in 2024-02, with the labels that each got.

#23 Feature and Style: Main homepage has proper navigation between pages and styling.
  ADS/_view/about.html
  ADS/_view/help.html
  ADS/_view/home.html
  ADS/_view/images/ADS.png
  ADS/_view/images/ads-corner.png
  ADS/_view/images/ads-high-resolution-logo.png
  ADS/_view/images/docScan.png
  ADS/_view/images/images
  ADS/_view/images/paper_background.jpg
  ADS/view/home.html
  ADS/view/index.html
Labels: frontend, Sprint 1

#24 feat: Added PDF Generator Page
  ADS/view/pdfgen.html
Labels: enhancement, additions, backend, Sprint 1

#26 bug: renamed _view into view
  ADS/_view/about.html
  ADS/_view/help.html
  ADS/_view/home.html
  ADS/_view/images/ADS.png
  ADS/_view/images/ads-corner.png
  ADS/_view/images/ads-high-resolution-logo.png
  ADS/_view/images/docScan.png
  ADS/_view/images/images
  ADS/_view/images/paper_background.jpg
Labels: bug

#29 Style: Updated styling to the Help page
  ADS/view/help.html
Labels: frontend, Sprint 1
